/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as VanityCreateRouteImport } from './routes/vanity-create'
import { Route as VanityCorporateRouteImport } from './routes/vanity-corporate'
import { Route as VanityRouteImport } from './routes/vanity'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyWinsRouteImport } from './routes/my-wins'
import { Route as MyBidsRouteImport } from './routes/my-bids'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HowToAuctionRouteImport } from './routes/how-to-auction'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ChallansRouteImport } from './routes/challans'
import { Route as BuyAdvanceNumbersRouteImport } from './routes/buy-advance-numbers'
import { Route as BiddingRouteImport } from './routes/bidding'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AuctionSeriesRouteImport } from './routes/auction-series'
import { Route as AdvanceNumbersRouteImport } from './routes/advance-numbers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PlatesIdRouteImport } from './routes/plates.$id'
import { Route as JoinAuctionIdRouteImport } from './routes/join-auction.$id'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as ChallansIdRouteImport } from './routes/challans.$id'
import { Route as AuctionsIdRouteImport } from './routes/auctions.$id'
import { Route as AuctionSeriesSeriesIdRouteImport } from './routes/auction-series.$seriesId'
import { Route as AdminWinnersRouteImport } from './routes/admin.winners'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminPlatesRouteImport } from './routes/admin.plates'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminAuctionsRouteImport } from './routes/admin.auctions'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const VanityCreateRoute = VanityCreateRouteImport.update({
  id: '/vanity-create',
  path: '/vanity-create',
  getParentRoute: () => rootRouteImport,
} as any)
const VanityCorporateRoute = VanityCorporateRouteImport.update({
  id: '/vanity-corporate',
  path: '/vanity-corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const VanityRoute = VanityRouteImport.update({
  id: '/vanity',
  path: '/vanity',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWinsRoute = MyWinsRouteImport.update({
  id: '/my-wins',
  path: '/my-wins',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBidsRoute = MyBidsRouteImport.update({
  id: '/my-bids',
  path: '/my-bids',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToAuctionRoute = HowToAuctionRouteImport.update({
  id: '/how-to-auction',
  path: '/how-to-auction',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallansRoute = ChallansRouteImport.update({
  id: '/challans',
  path: '/challans',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyAdvanceNumbersRoute = BuyAdvanceNumbersRouteImport.update({
  id: '/buy-advance-numbers',
  path: '/buy-advance-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const BiddingRoute = BiddingRouteImport.update({
  id: '/bidding',
  path: '/bidding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionSeriesRoute = AuctionSeriesRouteImport.update({
  id: '/auction-series',
  path: '/auction-series',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvanceNumbersRoute = AdvanceNumbersRouteImport.update({
  id: '/advance-numbers',
  path: '/advance-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatesIdRoute = PlatesIdRouteImport.update({
  id: '/plates/$id',
  path: '/plates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAuctionIdRoute = JoinAuctionIdRouteImport.update({
  id: '/join-auction/$id',
  path: '/join-auction/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)
const ChallansIdRoute = ChallansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChallansRoute,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuctionsRoute,
} as any)
const AuctionSeriesSeriesIdRoute = AuctionSeriesSeriesIdRouteImport.update({
  id: '/$seriesId',
  path: '/$seriesId',
  getParentRoute: () => AuctionSeriesRoute,
} as any)
const AdminWinnersRoute = AdminWinnersRouteImport.update({
  id: '/admin/winners',
  path: '/admin/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlatesRoute = AdminPlatesRouteImport.update({
  id: '/admin/plates',
  path: '/admin/plates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuctionsRoute = AdminAuctionsRouteImport.update({
  id: '/admin/auctions',
  path: '/admin/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advance-numbers': typeof AdvanceNumbersRoute
  '/auction-series': typeof AuctionSeriesRouteWithChildren
  '/auctions': typeof AuctionsRouteWithChildren
  '/bidding': typeof BiddingRoute
  '/buy-advance-numbers': typeof BuyAdvanceNumbersRoute
  '/challans': typeof ChallansRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-to-auction': typeof HowToAuctionRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/my-bids': typeof MyBidsRoute
  '/my-wins': typeof MyWinsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/terms': typeof TermsRoute
  '/vanity': typeof VanityRoute
  '/vanity-corporate': typeof VanityCorporateRoute
  '/vanity-create': typeof VanityCreateRoute
  '/winners': typeof WinnersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/plates': typeof AdminPlatesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/auction-series/$seriesId': typeof AuctionSeriesSeriesIdRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/challans/$id': typeof ChallansIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/join-auction/$id': typeof JoinAuctionIdRoute
  '/plates/$id': typeof PlatesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advance-numbers': typeof AdvanceNumbersRoute
  '/auction-series': typeof AuctionSeriesRouteWithChildren
  '/auctions': typeof AuctionsRouteWithChildren
  '/bidding': typeof BiddingRoute
  '/buy-advance-numbers': typeof BuyAdvanceNumbersRoute
  '/challans': typeof ChallansRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-to-auction': typeof HowToAuctionRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/my-bids': typeof MyBidsRoute
  '/my-wins': typeof MyWinsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/terms': typeof TermsRoute
  '/vanity': typeof VanityRoute
  '/vanity-corporate': typeof VanityCorporateRoute
  '/vanity-create': typeof VanityCreateRoute
  '/winners': typeof WinnersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/plates': typeof AdminPlatesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/auction-series/$seriesId': typeof AuctionSeriesSeriesIdRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/challans/$id': typeof ChallansIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/join-auction/$id': typeof JoinAuctionIdRoute
  '/plates/$id': typeof PlatesIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advance-numbers': typeof AdvanceNumbersRoute
  '/auction-series': typeof AuctionSeriesRouteWithChildren
  '/auctions': typeof AuctionsRouteWithChildren
  '/bidding': typeof BiddingRoute
  '/buy-advance-numbers': typeof BuyAdvanceNumbersRoute
  '/challans': typeof ChallansRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-to-auction': typeof HowToAuctionRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/my-applications': typeof MyApplicationsRoute
  '/my-bids': typeof MyBidsRoute
  '/my-wins': typeof MyWinsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/terms': typeof TermsRoute
  '/vanity': typeof VanityRoute
  '/vanity-corporate': typeof VanityCorporateRoute
  '/vanity-create': typeof VanityCreateRoute
  '/winners': typeof WinnersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/plates': typeof AdminPlatesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/auction-series/$seriesId': typeof AuctionSeriesSeriesIdRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/challans/$id': typeof ChallansIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/join-auction/$id': typeof JoinAuctionIdRoute
  '/plates/$id': typeof PlatesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advance-numbers'
    | '/auction-series'
    | '/auctions'
    | '/bidding'
    | '/buy-advance-numbers'
    | '/challans'
    | '/change-password'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/how-to-auction'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/my-applications'
    | '/my-bids'
    | '/my-wins'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/schedule'
    | '/terms'
    | '/vanity'
    | '/vanity-corporate'
    | '/vanity-create'
    | '/winners'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/auctions'
    | '/admin/members'
    | '/admin/plates'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/winners'
    | '/auction-series/$seriesId'
    | '/auctions/$id'
    | '/challans/$id'
    | '/invoices/$id'
    | '/join-auction/$id'
    | '/plates/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advance-numbers'
    | '/auction-series'
    | '/auctions'
    | '/bidding'
    | '/buy-advance-numbers'
    | '/challans'
    | '/change-password'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/how-to-auction'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/my-applications'
    | '/my-bids'
    | '/my-wins'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/schedule'
    | '/terms'
    | '/vanity'
    | '/vanity-corporate'
    | '/vanity-create'
    | '/winners'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/auctions'
    | '/admin/members'
    | '/admin/plates'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/winners'
    | '/auction-series/$seriesId'
    | '/auctions/$id'
    | '/challans/$id'
    | '/invoices/$id'
    | '/join-auction/$id'
    | '/plates/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advance-numbers'
    | '/auction-series'
    | '/auctions'
    | '/bidding'
    | '/buy-advance-numbers'
    | '/challans'
    | '/change-password'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/how-to-auction'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/my-applications'
    | '/my-bids'
    | '/my-wins'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/schedule'
    | '/terms'
    | '/vanity'
    | '/vanity-corporate'
    | '/vanity-create'
    | '/winners'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/auctions'
    | '/admin/members'
    | '/admin/plates'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/winners'
    | '/auction-series/$seriesId'
    | '/auctions/$id'
    | '/challans/$id'
    | '/invoices/$id'
    | '/join-auction/$id'
    | '/plates/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvanceNumbersRoute: typeof AdvanceNumbersRoute
  AuctionSeriesRoute: typeof AuctionSeriesRouteWithChildren
  AuctionsRoute: typeof AuctionsRouteWithChildren
  BiddingRoute: typeof BiddingRoute
  BuyAdvanceNumbersRoute: typeof BuyAdvanceNumbersRoute
  ChallansRoute: typeof ChallansRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowToAuctionRoute: typeof HowToAuctionRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  MyBidsRoute: typeof MyBidsRoute
  MyWinsRoute: typeof MyWinsRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ScheduleRoute: typeof ScheduleRoute
  TermsRoute: typeof TermsRoute
  VanityRoute: typeof VanityRoute
  VanityCorporateRoute: typeof VanityCorporateRoute
  VanityCreateRoute: typeof VanityCreateRoute
  WinnersRoute: typeof WinnersRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuctionsRoute: typeof AdminAuctionsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPlatesRoute: typeof AdminPlatesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWinnersRoute: typeof AdminWinnersRoute
  JoinAuctionIdRoute: typeof JoinAuctionIdRoute
  PlatesIdRoute: typeof PlatesIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vanity-create': {
      id: '/vanity-create'
      path: '/vanity-create'
      fullPath: '/vanity-create'
      preLoaderRoute: typeof VanityCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vanity-corporate': {
      id: '/vanity-corporate'
      path: '/vanity-corporate'
      fullPath: '/vanity-corporate'
      preLoaderRoute: typeof VanityCorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vanity': {
      id: '/vanity'
      path: '/vanity'
      fullPath: '/vanity'
      preLoaderRoute: typeof VanityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-wins': {
      id: '/my-wins'
      path: '/my-wins'
      fullPath: '/my-wins'
      preLoaderRoute: typeof MyWinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bids': {
      id: '/my-bids'
      path: '/my-bids'
      fullPath: '/my-bids'
      preLoaderRoute: typeof MyBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-auction': {
      id: '/how-to-auction'
      path: '/how-to-auction'
      fullPath: '/how-to-auction'
      preLoaderRoute: typeof HowToAuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challans': {
      id: '/challans'
      path: '/challans'
      fullPath: '/challans'
      preLoaderRoute: typeof ChallansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-advance-numbers': {
      id: '/buy-advance-numbers'
      path: '/buy-advance-numbers'
      fullPath: '/buy-advance-numbers'
      preLoaderRoute: typeof BuyAdvanceNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bidding': {
      id: '/bidding'
      path: '/bidding'
      fullPath: '/bidding'
      preLoaderRoute: typeof BiddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction-series': {
      id: '/auction-series'
      path: '/auction-series'
      fullPath: '/auction-series'
      preLoaderRoute: typeof AuctionSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advance-numbers': {
      id: '/advance-numbers'
      path: '/advance-numbers'
      fullPath: '/advance-numbers'
      preLoaderRoute: typeof AdvanceNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plates/$id': {
      id: '/plates/$id'
      path: '/plates/$id'
      fullPath: '/plates/$id'
      preLoaderRoute: typeof PlatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-auction/$id': {
      id: '/join-auction/$id'
      path: '/join-auction/$id'
      fullPath: '/join-auction/$id'
      preLoaderRoute: typeof JoinAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/challans/$id': {
      id: '/challans/$id'
      path: '/$id'
      fullPath: '/challans/$id'
      preLoaderRoute: typeof ChallansIdRouteImport
      parentRoute: typeof ChallansRoute
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/auction-series/$seriesId': {
      id: '/auction-series/$seriesId'
      path: '/$seriesId'
      fullPath: '/auction-series/$seriesId'
      preLoaderRoute: typeof AuctionSeriesSeriesIdRouteImport
      parentRoute: typeof AuctionSeriesRoute
    }
    '/admin/winners': {
      id: '/admin/winners'
      path: '/admin/winners'
      fullPath: '/admin/winners'
      preLoaderRoute: typeof AdminWinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plates': {
      id: '/admin/plates'
      path: '/admin/plates'
      fullPath: '/admin/plates'
      preLoaderRoute: typeof AdminPlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auctions': {
      id: '/admin/auctions'
      path: '/admin/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AdminAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuctionSeriesRouteChildren {
  AuctionSeriesSeriesIdRoute: typeof AuctionSeriesSeriesIdRoute
}

const AuctionSeriesRouteChildren: AuctionSeriesRouteChildren = {
  AuctionSeriesSeriesIdRoute: AuctionSeriesSeriesIdRoute,
}

const AuctionSeriesRouteWithChildren = AuctionSeriesRoute._addFileChildren(
  AuctionSeriesRouteChildren,
)

interface AuctionsRouteChildren {
  AuctionsIdRoute: typeof AuctionsIdRoute
}

const AuctionsRouteChildren: AuctionsRouteChildren = {
  AuctionsIdRoute: AuctionsIdRoute,
}

const AuctionsRouteWithChildren = AuctionsRoute._addFileChildren(
  AuctionsRouteChildren,
)

interface ChallansRouteChildren {
  ChallansIdRoute: typeof ChallansIdRoute
}

const ChallansRouteChildren: ChallansRouteChildren = {
  ChallansIdRoute: ChallansIdRoute,
}

const ChallansRouteWithChildren = ChallansRoute._addFileChildren(
  ChallansRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvanceNumbersRoute: AdvanceNumbersRoute,
  AuctionSeriesRoute: AuctionSeriesRouteWithChildren,
  AuctionsRoute: AuctionsRouteWithChildren,
  BiddingRoute: BiddingRoute,
  BuyAdvanceNumbersRoute: BuyAdvanceNumbersRoute,
  ChallansRoute: ChallansRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowToAuctionRoute: HowToAuctionRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  LoginRoute: LoginRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  MyBidsRoute: MyBidsRoute,
  MyWinsRoute: MyWinsRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ScheduleRoute: ScheduleRoute,
  TermsRoute: TermsRoute,
  VanityRoute: VanityRoute,
  VanityCorporateRoute: VanityCorporateRoute,
  VanityCreateRoute: VanityCreateRoute,
  WinnersRoute: WinnersRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuctionsRoute: AdminAuctionsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPlatesRoute: AdminPlatesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWinnersRoute: AdminWinnersRoute,
  JoinAuctionIdRoute: JoinAuctionIdRoute,
  PlatesIdRoute: PlatesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
